In [32]:
import numpy as np

In [33]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [35]:
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
d = np.ones((2,2))
print(d)

[[1. 1.]
 [1. 1.]]


In [37]:
a1 = np.array([4,5,6,7])
print(a,a1)

[1 2 3 4] [4 5 6 7]


In [38]:
add = a+a1
print(add)

[ 5  7  9 11]


In [39]:
print(a-a1)

[-3 -3 -3 -3]


In [40]:
print(a*a1)

[ 4 10 18 28]


In [41]:
d = np.array([[1,2],[3,4]])
e = np.array([[5,6],[7,8]])

In [45]:
d = a.reshape(2,2)
e = a1.reshape(2,2)

print(d*e)
print()
print(np.dot(d,e))

[[ 4 10]
 [18 28]]

[[16 19]
 [36 43]]
